% % https://mtex-toolbox.github.io/CrystalReferenceSystem.html
function ebsd = rotateBasisVectors(CS)
    if strcmpi(CS.lattice,'hexagonal')
            CShcp = crystalSymmetry('SpaceId',cprPhase.spacegroup,...
                [cprPhase.a cprPhase.b cprPhase.c],...
                [cprPhase.alpha*degree,cprPhase.beta*degree,cprPhase.gamma*degree],...
                'X||a', 'Y||b*', 'Z||c',...
                'mineral', CS.mineral,...
                'color',CS.color);
            oriOld = ebsd.all(ebsd.all.mineralList(ii)).orientations;
            oriNew = transformReferenceFrame(oriOld,CShcp);
            ebsd.all(ebsd.all.mineralList(ii)).orientations = oriNew;
            screenPrint('Step',['Rotated the lattice basis vectors of phase: ''',CS.mineral,'''']);
            
    end
